### ISSUE TITLE
Strip `PartIDTag` from outputs of a computation

### ISSUE THREAD

**Issue by inducer** [inducer/pytato#307]
I was debugging the failure in https://github.com/inducer/grudge/runs/5982131517?check_suite_focus=true
```
Traceback (most recent call last):
  File "/home/runner/work/grudge/grudge/examples/wave/wave-op-mpi.py", line 335, in <module>
    main(cl.create_some_context,
  File "/home/runner/work/grudge/grudge/examples/wave/wave-op-mpi.py", line 278, in main
    fields = compiled_lsrk45_step(actx, fields, t, dt, compiled_rhs)
  File "/home/runner/work/grudge/grudge/grudge/shortcuts.py", line 55, in compiled_lsrk45_step
    y, residual  = update(y, a, b, h, residual, rhs_val)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.10/site-packages/arraycontext/impl/pytato/compile.py", line 363, in __call__
    compiled_func = self._dag_to_compiled_func(
  File "/home/runner/work/grudge/grudge/grudge/array_context.py", line 143, in _dag_to_compiled_func
    distributed_partition = find_distributed_partition(dict_of_named_arrays)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.10/site-packages/pytato/distributed.py", line 914, in find_distributed_partition
    partitioned_outputs = make_dict_of_named_arrays({
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.10/site-packages/pytato/distributed.py", line 915, in <dictcomp>
    name: part_id_tag_assigner(subexpr, stored_ary_to_part_id[subexpr])
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.10/site-packages/pytato/transform.py", line 169, in __call__
    return self.rec(expr, *args, **kwargs)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.10/site-packages/pytato/distributed.py", line 792, in rec
    result = super().rec(expr, user_part_id)
[snip]
pytools.tag.NonUniqueTagError: Multiple tags are direct subclasses of the following UniqueTag(s): PartIDTag
```
and it occurred to me that we never strip the `PartIDTag` from outputs of distributed computations. While I haven't verified that this is the source of this bug, it seems plausible:
- The non-unique tag occurs on a `Placeholder`, which could quite plausibly have gotten it from the output of another distributed computation.
- https://github.com/inducer/grudge/pull/252 is the first time that two different `compile`d operators occur in one program (with different partitions: the time stepper only has one part since it's all local, the wave operator will have two)

Possibly, these additional tags may also lead to spurious recompilations because things make arrays look different even when they aren't.

The above issue is easy to reproduce: just run
```
mpiexec -np 2 python wave-op-mpi.py --lazy
```
on the branch from https://github.com/inducer/grudge/pull/252.

cc @kaushikcfd

**Comment by inducer** [comment]
#308
